//! Minimal Kitty graphics transport for application-owned frame presentation.

use base64::{Engine, engine::general_purpose::STANDARD};
use std::{
    fmt,
    io::{self, Write},
    num::NonZeroU32,
};

const BASE64_CHUNK_SIZE: usize = 4096;
const APC_START: &[u8] = b"\x1b_G";
const STRING_TERMINATOR: &[u8] = b"\x1b\\";
const SYNCHRONIZED_UPDATE_START: &[u8] = b"\x1b[?2026h";
const SYNCHRONIZED_UPDATE_END: &[u8] = b"\x1b[?2026l";

/// An application-owned Kitty image ID. Zero is reserved by the protocol.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ImageId(NonZeroU32);

impl ImageId {
    pub fn new(value: u32) -> Result<Self, Error> {
        NonZeroU32::new(value)
            .map(Self)
            .ok_or(Error::ReservedIdentifier { kind: "image" })
    }

    fn get(self) -> u32 {
        self.0.get()
    }
}

/// An application-owned Kitty placement ID. Zero is reserved by the protocol.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PlacementId(NonZeroU32);

impl PlacementId {
    pub fn new(value: u32) -> Result<Self, Error> {
        NonZeroU32::new(value)
            .map(Self)
            .ok_or(Error::ReservedIdentifier { kind: "placement" })
    }

    fn get(self) -> u32 {
        self.0.get()
    }
}

/// The terminal-cell rectangle occupied by the preview.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PreviewArea {
    pub column: u16,
    pub row: u16,
    pub columns: u16,
    pub rows: u16,
    pub z_index: i32,
}

impl PreviewArea {
    pub fn new(column: u16, row: u16, columns: u16, rows: u16) -> Result<Self, Error> {
        if column == 0 || row == 0 || columns == 0 || rows == 0 {
            return Err(Error::InvalidPreviewArea);
        }

        Ok(Self {
            column,
            row,
            columns,
            rows,
            z_index: 0,
        })
    }

    pub fn with_z_index(mut self, z_index: i32) -> Self {
        self.z_index = z_index;
        self
    }
}

/// A single raw sRGB RGBA frame generated by the animation renderer.
#[derive(Clone, Copy, Debug)]
pub struct RgbaFrame<'a> {
    pub width: u32,
    pub height: u32,
    pub pixels: &'a [u8],
}

impl<'a> RgbaFrame<'a> {
    pub fn new(width: u32, height: u32, pixels: &'a [u8]) -> Result<Self, Error> {
        if width == 0 || height == 0 {
            return Err(Error::InvalidFrameDimensions);
        }

        let expected = usize::try_from(width)
            .ok()
            .and_then(|width| width.checked_mul(usize::try_from(height).ok()?))
            .and_then(|pixels| pixels.checked_mul(4))
            .ok_or(Error::FrameTooLarge)?;
        if pixels.len() != expected {
            return Err(Error::InvalidFrameLength {
                expected,
                actual: pixels.len(),
            });
        }

        Ok(Self {
            width,
            height,
            pixels,
        })
    }
}

/// Selects whether the same image ID or alternating image IDs present frames.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BufferingStrategy {
    /// Retransmits and re-places the same image ID. Use only for a terminal-specific fast path.
    Single,
    /// Uploads into an unplaced image ID, then atomically presents it over the previous image.
    Double,
}

/// Encodes and presents raw RGBA frames using the Kitty graphics protocol.
///
/// The caller selects the strategy after terminal-specific capability detection. The presenter
/// owns only the protocol state, so rendering and Ratatui layout remain independent.
#[derive(Debug)]
pub struct Presenter {
    strategy: BufferingStrategy,
    placement_id: PlacementId,
    area: PreviewArea,
    front: ImageId,
    back: Option<ImageId>,
    has_front_frame: bool,
}

impl Presenter {
    pub fn single(image_id: ImageId, placement_id: PlacementId, area: PreviewArea) -> Self {
        Self {
            strategy: BufferingStrategy::Single,
            placement_id,
            area,
            front: image_id,
            back: None,
            has_front_frame: false,
        }
    }

    pub fn double(
        first_image_id: ImageId,
        second_image_id: ImageId,
        placement_id: PlacementId,
        area: PreviewArea,
    ) -> Result<Self, Error> {
        if first_image_id == second_image_id {
            return Err(Error::DuplicateBufferIdentifier);
        }

        Ok(Self {
            strategy: BufferingStrategy::Double,
            placement_id,
            area,
            front: first_image_id,
            back: Some(second_image_id),
            has_front_frame: false,
        })
    }

    pub fn strategy(&self) -> BufferingStrategy {
        self.strategy
    }

    /// Writes a full frame and commits the corresponding buffering-state transition only after
    /// the terminal stream is successfully flushed.
    pub fn present<W: Write>(&mut self, writer: &mut W, frame: RgbaFrame<'_>) -> Result<(), Error> {
        let next = self.back.unwrap_or(self.front);
        let mut output = upload_frame(next, frame);

        match self.strategy {
            BufferingStrategy::Single => {
                output.extend(synchronized(|commands| {
                    place(commands, next, self.placement_id, self.area);
                }));
            }
            BufferingStrategy::Double => {
                output.extend(synchronized(|commands| {
                    // The incoming image has a higher z-index during the handoff so it wins the
                    // brief overlap before the old placement is removed.
                    place(
                        commands,
                        next,
                        self.placement_id,
                        self.area.with_z_index(self.area.z_index.saturating_add(1)),
                    );
                    if self.has_front_frame {
                        delete_placement(commands, self.front, self.placement_id);
                    }
                }));
            }
        }

        writer.write_all(&output)?;
        writer.flush()?;

        if self.strategy == BufferingStrategy::Double {
            self.back = Some(self.front);
            self.front = next;
        }
        self.has_front_frame = true;
        Ok(())
    }

    /// Removes every placement and releases image data allocated by this presenter.
    pub fn clear<W: Write>(&mut self, writer: &mut W) -> Result<(), Error> {
        let mut output = Vec::new();
        delete_image_data(&mut output, self.front);
        if let Some(back) = self.back {
            delete_image_data(&mut output, back);
        }
        writer.write_all(&output)?;
        writer.flush()?;
        self.has_front_frame = false;
        Ok(())
    }
}

fn upload_frame(image_id: ImageId, frame: RgbaFrame<'_>) -> Vec<u8> {
    let encoded = STANDARD.encode(frame.pixels);
    let chunk_count = encoded.len().div_ceil(BASE64_CHUNK_SIZE);
    let mut output = Vec::with_capacity(encoded.len() + chunk_count * 40);

    for (index, chunk) in encoded.as_bytes().chunks(BASE64_CHUNK_SIZE).enumerate() {
        let more = usize::from(index + 1 < chunk_count);
        output.extend_from_slice(APC_START);
        if index == 0 {
            push_format(
                &mut output,
                format_args!(
                    "a=t,f=32,s={},v={},i={},q=2,m={more};",
                    frame.width,
                    frame.height,
                    image_id.get(),
                ),
            );
        } else {
            push_format(&mut output, format_args!("m={more};"));
        }
        output.extend_from_slice(chunk);
        output.extend_from_slice(STRING_TERMINATOR);
    }

    output
}

fn synchronized(commands: impl FnOnce(&mut Vec<u8>)) -> Vec<u8> {
    let mut output = Vec::new();
    output.extend_from_slice(SYNCHRONIZED_UPDATE_START);
    output.extend_from_slice(b"\x1b7");
    commands(&mut output);
    output.extend_from_slice(b"\x1b8");
    output.extend_from_slice(SYNCHRONIZED_UPDATE_END);
    output
}

fn place(output: &mut Vec<u8>, image_id: ImageId, placement_id: PlacementId, area: PreviewArea) {
    push_format(output, format_args!("\x1b[{};{}H", area.row, area.column));
    output.extend_from_slice(APC_START);
    push_format(
        output,
        format_args!(
            "a=p,i={},p={},c={},r={},z={},C=1,q=2;",
            image_id.get(),
            placement_id.get(),
            area.columns,
            area.rows,
            area.z_index,
        ),
    );
    output.extend_from_slice(STRING_TERMINATOR);
}

fn delete_placement(output: &mut Vec<u8>, image_id: ImageId, placement_id: PlacementId) {
    output.extend_from_slice(APC_START);
    push_format(
        output,
        format_args!("a=d,d=i,i={},p={},q=2;", image_id.get(), placement_id.get()),
    );
    output.extend_from_slice(STRING_TERMINATOR);
}

fn delete_image_data(output: &mut Vec<u8>, image_id: ImageId) {
    output.extend_from_slice(APC_START);
    push_format(output, format_args!("a=d,d=I,i={},q=2;", image_id.get()));
    output.extend_from_slice(STRING_TERMINATOR);
}

fn push_format(output: &mut Vec<u8>, arguments: fmt::Arguments<'_>) {
    use std::io::Write as _;
    output
        .write_fmt(arguments)
        .expect("writing to a Vec cannot fail");
}

#[derive(Debug)]
pub enum Error {
    ReservedIdentifier { kind: &'static str },
    DuplicateBufferIdentifier,
    InvalidPreviewArea,
    InvalidFrameDimensions,
    FrameTooLarge,
    InvalidFrameLength { expected: usize, actual: usize },
    Io(io::Error),
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ReservedIdentifier { kind } => write!(formatter, "{kind} ID zero is reserved"),
            Self::DuplicateBufferIdentifier => {
                write!(formatter, "double buffering requires two image IDs")
            }
            Self::InvalidPreviewArea => write!(
                formatter,
                "preview coordinates and dimensions must be nonzero"
            ),
            Self::InvalidFrameDimensions => write!(formatter, "frame dimensions must be nonzero"),
            Self::FrameTooLarge => write!(formatter, "frame dimensions exceed addressable memory"),
            Self::InvalidFrameLength { expected, actual } => {
                write!(
                    formatter,
                    "RGBA frame has {actual} bytes; expected {expected}"
                )
            }
            Self::Io(error) => write!(formatter, "terminal output failed: {error}"),
        }
    }
}

impl std::error::Error for Error {}

impl From<io::Error> for Error {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn frame() -> RgbaFrame<'static> {
        RgbaFrame::new(1, 1, &[0x01, 0x02, 0x03, 0x04]).unwrap()
    }

    fn area() -> PreviewArea {
        PreviewArea::new(2, 3, 4, 5).unwrap()
    }

    #[test]
    fn rejects_invalid_rgba_lengths() {
        let error = RgbaFrame::new(2, 1, &[0; 7]).unwrap_err();
        assert!(matches!(error, Error::InvalidFrameLength { .. }));
    }

    #[test]
    fn single_buffer_reuses_its_image_id() {
        let mut presenter = Presenter::single(
            ImageId::new(11).unwrap(),
            PlacementId::new(5).unwrap(),
            area(),
        );
        let mut output = Vec::new();
        presenter.present(&mut output, frame()).unwrap();
        presenter.present(&mut output, frame()).unwrap();

        let output = String::from_utf8(output).unwrap();
        assert_eq!(output.matches("a=t,f=32,s=1,v=1,i=11").count(), 2);
        assert!(!output.contains("a=d,d=i"));
    }

    #[test]
    fn double_buffer_alternates_ids_and_deletes_the_old_placement() {
        let mut presenter = Presenter::double(
            ImageId::new(11).unwrap(),
            ImageId::new(12).unwrap(),
            PlacementId::new(5).unwrap(),
            area(),
        )
        .unwrap();
        let mut output = Vec::new();
        presenter.present(&mut output, frame()).unwrap();
        presenter.present(&mut output, frame()).unwrap();

        let output = String::from_utf8(output).unwrap();
        assert!(output.contains("a=t,f=32,s=1,v=1,i=12"));
        assert!(output.contains("a=t,f=32,s=1,v=1,i=11"));
        assert!(output.contains("a=d,d=i,i=12,p=5,q=2;"));
        assert_eq!(output.matches("\x1b[?2026h").count(), 2);
    }

    #[test]
    fn clear_releases_every_owned_image_id() {
        let mut presenter = Presenter::double(
            ImageId::new(11).unwrap(),
            ImageId::new(12).unwrap(),
            PlacementId::new(5).unwrap(),
            area(),
        )
        .unwrap();
        let mut output = Vec::new();
        presenter.clear(&mut output).unwrap();

        let output = String::from_utf8(output).unwrap();
        assert!(output.contains("a=d,d=I,i=11,q=2;"));
        assert!(output.contains("a=d,d=I,i=12,q=2;"));
    }
}
